### PR TITLE
fix dataURiHtmlHeader case according to https://developer.mozilla.org…

### PR DESCRIPTION
**Pull request by bung87**
…/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Nope, you break it, sorry.

I think that should be the reverse, for the OS that wont take it, 
you should encode it first if needed or use the HTML UTF-8 meta tag.


temp

**Comment by bung87** [comment]
hmm may just using base64 , event base64 the demo still not inject css, encodeUrl just for simple case, without it , it can't render single html tag, the html source show empty inside body.

**Comment by juancarlospaco** [comment]
Are you using HTML UTF-8 meta tag?.
Are you tried full path?. If you `echo` the `path` what is shown?.

Maybe that `const` need to be abstracted into a `template` and add some `assert` and checks.

**Comment by bung87** [comment]
I just pass`"<textarea></textarea>"` for testing keyboard shortcut.

**Comment by juancarlospaco** [comment]
But if you encode it before passing it, then it works?.
Maybe that should be the way, as it is now works for Linux and Windows.

If you get it to work, send a helper `template` for OS X only, with a `when defined(osx):`.

**Comment by bung87** [comment]
yes, the demo case break because it contains css and js , should be base64 encoded, but still not inject css on my mac. will check it later

**Pull request merged**
